# Generated by Django 5.0.6 on 2024-06-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='Name',
            field=models.CharField(choices=[('margherita', 'Margherita'), ('pepperoni', 'Pepperoni'), ('vegetarian', 'Vegetarian')], max_length=100),
        ),
    ]
